version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    branches:
      only:
        - develop
        - master
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: yarn install
          - run: lerna run test
          - run: lerna run build

  publish:
    branches:
      only:
        - master
    executor:
      name: node/default
    steps:
      - run: lerna publish --conventional-prerelease --no-changelog

  merge-back:
    branches:
      only:
        - master
    executor:
      name: node/default
    steps:
      - run: git checkout develop
      - run: git merge master

workflows:
  build-and-test:
    jobs:
      - build-and-test
  publish:
    jobs:
      - publish
  merge-back:
    jobs:
      - merge-back
