version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lerna run test
            - run: yarn lerna run build

  publish:
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ~/repo
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

            - run: yarn install
            - run: yarn build

            - run: git config user.email $GIT_EMAIL
            - run: git config user.name $GIT_USERNAME

            - run: yarn lerna publish --conventional-prerelease --yes

  merge-back:
    executor:
      name: node/default
    steps:
      - checkout
      - run: git config user.email $GIT_EMAIL
      - run: git config user.name $GIT_USERNAME
      - run: git checkout develop
      - run: git merge master --ff --message 'Merge back release'
      - run: git push origin

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - develop
                - /^feat(ure)?\/.+/
  build-and-publish:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      - publish:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
      - merge-back:
          requires:
            - publish
          filters:
            branches:
              only:
                - master
