version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lerna run test
            - run: yarn lerna run build

  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn lerna publish --conventional-prerelease --no-changelog --yes

  merge-back:
    executor:
      name: node/default
    steps:
      - run: git checkout develop
      - run: git merge master

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - develop
                - master
                - /^feat(ure)?\/.+/
      - publish:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
      - merge-back:
          requires:
            - publish
          filters:
            branches:
              only:
                - master
